---
# tasks file for installdocker
- name: Update all Ubuntu packages 
  become: true
  become_method: "sudo"
  apt:
    upgrade: "dist"
    update_cache: true
  when: ansible_distribution == 'Ubuntu'

- name: Install docker for Ubuntu 
  become: true
  become_method: "sudo"
  command: "apt-get update && apt install docker.io -y && sudo snap install docker"
  when: ansible_distribution == 'Ubuntu'


- name: Deploy docker app for Ubuntu 
  become: true
  become_method: "sudo"
  command: "docker run -d -p 80:80 vietlt215/lab01-angular-webapp"
  when: ansible_distribution == 'Ubuntu'
